name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Download code base"
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: step2
        run: echo "Create the microservices image"
      - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        uses: docker/login-action@v3.0.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USR }} 
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            francielrezende/conversao-temperatura:${{github.run_number}}
            francielrezende/conversao-temperatura:latest
      - name: step3
        run: echo "Push the images to the repository (Docker HUB"
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: step1
        run: echo "Download code base"
      - name: step2
        run: echo "Authentication on AWS"
      - name: step3
        run: echo "Microservices deployment on kubernetes"
      
